services:
    db:
        image: postgres:16
        container_name: mini-horta-postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mini_horta
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    web:
        build: .
        container_name: mini-horta-next
        env_file:
            - .env
        environment:
            DATABASE_URL: postgresql://postgres:postgres@db:5432/mini_horta
            NEXT_PUBLIC_APP_NAME: Horta Fácil
        ports:
            - "3000:3000"
        depends_on:
            - db

volumes:
    postgres_data:
